name: book_manager
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  sqflite: ^2.4.2
  path: ^1.9.1
  # Ajout pour supporter desktop
  sqflite_common_ffi: ^2.3.0+2
  sqlite3_flutter_libs: ^0.5.33
  # BLoC dependencies
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Web support for SQLite
  sqflite_common_ffi_web: ^0.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true